// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application';

import AlertsController from './alerts_controller';
application.register('alerts', AlertsController);

import DropdownController from './dropdown_controller';
application.register('dropdown', DropdownController);

import HelloController from './hello_controller';
application.register('hello', HelloController);

import ModalController from './modal_controller';
application.register('modal', ModalController);

import NestedFormController from './nested_form_controller';
application.register('nested-form', NestedFormController);

import PhoneFormatController from './phone_format_controller';
application.register('phone-format', PhoneFormatController);

import SearchableDropdownController from './searchable_dropdown_controller';
application.register('searchable-dropdown', SearchableDropdownController);

import SelectController from './select_controller';
application.register('select', SelectController);

import ToggleController from './toggle_controller';
application.register('toggle', ToggleController);

import TomSelectController from './tom_select_controller';
application.register('tom-select', TomSelectController);

import TabsController from './tabs_controller';
application.register('tabs', TabsController);

import ClientTypeController from './client_type_controller';
application.register('client-type', ClientTypeController);

